config/routes.rb
Stock::Application.routes.draw do
  resources :addresses

	root to: 'products#index'

  resources :orders

  resources :order_items

  resources :products

	match '/auth/:provider/callback', to: 'sessions#create'

	match "/login" => redirect("/auth/twitter"), as: :login
	match "/logout" => "sessions#destroy", as: :logout

	resources :orders do
		member do
		  put :purchase
		end
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :user, :status, :address

	has_many :order_items, dependent: :destroy
	belongs_to :user
	belongs_to :address

	def total
		total_value = 0
		order_items.each do |item|
			total_value += item.subtotal
		end
		return total_value
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.all
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def new
    @order = current_user.orders.new
  end

  def create
		
    @order = current_user.orders.new(params[:order])
    if @order.save
      redirect_to @order, :notice => "Successfully created order."
    else
      render :action => 'new'
    end
  end

  def edit
    @order = current_user.orders.find(params[:id])
  end

  def update
    @order = current_user.orders.find(params[:id])
    if @order.update_attributes(params[:address_id])
      redirect_to @order, :notice  => "Successfully updated order."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @order = current_user.orders.find(params[:id])
    @order.destroy
    redirect_to products_path, :notice => "Successfully destroyed order."
  end

	def purchase
		# Find the order
		# Set the address_id
		# Change the status to "submitted"
		# Save it
		# Remove the order_id from the session so they can't edit it
		# Display a thank you page with an order summary
		@order = current_user.orders.last
		@order.address = params[:address_id]
		@order.status = "submitted"
		@order.save
		session[:order_id] = nil
		redirect_to orders_path, :notice => "Thank you for buying in our shop."
	end
end

app/helpers/orders_helper.rb
module OrdersHelper

end

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </p>
  <p>
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/orders/edit.html.erb
<% title "Edit Order" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @order %> |
  <%= link_to "View All", orders_path %>
</p>

app/views/orders/index.html.erb
<% title "Orders" %>

<table>
  <tr>
    <th>User</th>
    <th>Status</th>
  </tr>
  <% for order in @orders %>
    <tr>
      <td><%= order.user_id %></td>
      <td><%= order.status %></td>
      <td><%= link_to "Show", order %></td>
      <td><%= link_to "Edit", edit_order_path(order) %></td>
      <td><%= link_to "Destroy", order, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Order", new_order_path %></p>

app/views/orders/new.html.erb
<% title "New Order" %>

<%= render 'form' %>

<p><%= link_to "Back to List", orders_path %></p>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<table>
  <tr>
    <th>Customer</th>
    <td><%= @order.user.name if @order.user %></td>
  </tr>
  <tr>
    <th>Status:</th>
    <td><%= @order.status %></td>
  </tr>
  <tr>
    <th>Items:</th>
    <td><%= @order.order_items.count %></td>
  </tr>
  <tr>
    <th>Items</th>
    <th>Title</th>
    <th>Quantity</th>
		<th>Stock:</th>
    <th>Unit Price</th>
    <th>Subtotal</th>
  </tr>
  <% @order.order_items.each do |item| %>
		<tr>
			<td><%= image_tag "products/#{item.product.image_url}" %></td>
			<td><%= item.product.title %></td>
			<td><%= link_to item.quantity, edit_order_item_path(item) %></td>
			<td><%= print_stock item.product.stock ,item.quantity %></td>
			<td><%= print_price item.product.price %></td>
			<td><%= print_price item.subtotal %></td>
			<td><%= link_to "Remove", item, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>	
	<% end %>

	<tr>
		<th>Shipping to:</th>
		<td>
			<%= form_for @order, url: purchase_order_path(@order), method: :put do |f| %>
				<%= f.select :address_id, current_user.addresses.collect{|a| [a.to_s, a.id]} if !current_user.nil? %>
				<%= f.submit "Submit Order" %>
			<% end %>
		</td>
		<td width="100">
			<% if current_user %>
				<%= link_to "Add new a'DRESS", addresses_path + "/new" %>
			<% end %>
		</td>
	</tr>

	</tr>
	<tr>
		<th>
			TOTAL:
		</th>

		<th>
			<%= print_price @order.total %>
		</th>
	</tr>
</table>