config/routes.rb
Stock::Application.routes.draw do
  resources :addresses

	root to: 'products#index'

  resources :orders

  resources :order_items

  resources :products

	match '/auth/:provider/callback', to: 'sessions#create'

	match "/login" => redirect("/auth/twitter"), as: :login
	match "/logout" => "sessions#destroy", as: :logout

	resources :orders do
		member do
		  put :purchase
		end
	end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :price, :description, :image_url
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, :notice => "Successfully destroyed product."
  end
end

app/helpers/products_helper.rb
module ProductsHelper
	def print_price(price)
		number_to_currency price, unit: "$"
	end

	def print_stock(stock, requested = 1)
		if stock <= 0
			return "Out of stock"			
		elsif stock >= requested
			return "In stock: " + stock.to_s
		elsif stock < requested
			return "Insufficient Stock"
		end
	end

end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </p>
	<p>
    <%= f.label :stock %><br />
    <%= f.text_field :stock %>
  </p>
  <p><%= f.submit %></p>
<% end %>
b

app/views/products/edit.html.erb
<% title "Edit Product" %>

<%= render 'form' %>

b

<p>
  <%= link_to "Show123", @product %> |
  <%= link_to "View All", products_path %>
</p>

a

app/views/products/index.html.erb
<% title "Products" %>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Description</th>
    <th>Image Url</th>
		<th>In Stock</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag "products/#{product.image_url}" %></td>
		  <td><span class="product_title"><%= product.title %></span><%= product.description %></td>
		  <td><%= print_price(product.price) %></td>
			<td><%= product.image_url %></td>
			<td><%= print_stock product.stock  %></td>
			<td><%= button_to "Add to Cart", order_items_path(product_id: product.id) %></td>
			<td><%= link_to "Show", product_path(product) %></td>			
			<td><%= link_to "Destroy", product_path(product), :confirm => 'Are you sure?', :method => :delete %> </td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Create a New Product", new_product_path %></p>

app/views/products/new.html.erb
<% title "New Product" %>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

app/views/products/show.html.erb
<% title "Product" %>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Image Url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>