config/routes.rb
Stock::Application.routes.draw do
  resources :addresses

	root to: 'products#index'

  resources :orders

  resources :order_items

  resources :products

	match '/auth/:provider/callback', to: 'sessions#create'

	match "/login" => redirect("/auth/twitter"), as: :login
	match "/logout" => "sessions#destroy", as: :logout

	resources :orders do
		member do
		  put :purchase
		end
	end

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodWorks - Products: <%= controller.action_name %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
		<div class="wrapper">
			<div class="header">
			  <h1>All products</h1>
			  <p>Your Online Grocery</p>
			</div>

			<%= link_to "Products", products_path %>
			<%= link_to "Orders", orders_path %>			
				
			<p style="color: green"><%= flash[:notice] %></p>

			<div id="account">
				<% if current_user %>
					<span>Welcome, <%= current_user.name %></span>
					<%= link_to "logout", logout_path, id: "login" %>
				<% else %>
					<%= link_to "login", login_path, id: "logout" %>
				<% end %>
			</div>

			<div class="sidebar">
			  (sidebar)
			</div>

			<div class="main">
			  <%= yield %>
			</div>

			<div class="footer">
			  FoodWorks Online Grocery<br/>
			  A Rails Jumpstart Project
			</div>
		</div>
	</body>
</html>